### ISSUE TITLE
GUAGE or GAUGE

### ISSUE THREAD

**Issue by larspehrsson** [andrewhodel/rrd#1]
GUAGE is incorrect. GAUGE is correct.

**Comment by andrewhodel** [comment]
Thanks!

https://github.com/andrewhodel/rrd/commit/7ee4028f43003a7d6de4fa8dab6cd06da24fa6a6

**Comment by andrewhodel** [comment]
@larspehrsson 

It was because of the spelling of the word language even though I look at it correctly.
